name: build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debug-windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.408
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.406
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.200
    - name: Clean
      run: dotnet clean --configuration Debug && dotnet nuget locals all --clear
      working-directory: Source
    - name: Install dependencies
      run: dotnet restore
      working-directory: Source
    - name: Build
      run: dotnet build --configuration Debug --no-restore
      working-directory: Source
    - name: Test
      run: dotnet test --configuration Debug --no-build --verbosity normal
      working-directory: Source

  release-windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.408
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.406
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.200
    - name: Clean
      run: dotnet clean --configuration Release && dotnet nuget locals all --clear
      working-directory: Source
    - name: Install dependencies
      run: dotnet restore
      working-directory: Source
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: Source
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      working-directory: Source
